"""Material certificate (inspection certificate 3.1, EN 10204:2004) of one supplier batch: generated by the
supplier portal when the batch is despatched, attached to the HandoverDocumentation of the batch AAS.

Content: supplier letterhead, certificate and despatch advice numbers, customer and article numbers, batch,
quantity, production date, material designation, chemical analysis / material properties / dimensional check
against the specified limits, recycled content, statement of the inspection representative. One A4 page,
written with the minimal PDF writer (vf_common.pdf).

`uv run python -m supplier.certificate [out.pdf]` writes the sample of the blueprint lot DGP-260914-F.
"""

from __future__ import annotations

import sys
from pathlib import Path

from vf_common.pdf import Page, render

from .batches import BatchRecord, Measurement

BLUE, GREY, GREEN = (0.32, 0.22, 0.12), (0.43, 0.45, 0.47), (0.1, 0.5, 0.25)
LEFT, VALUE_X = 50.0, 200.0
COLUMNS = (LEFT, 300.0, 360.0, 420.0, 490.0)
GROUPS = {"analysis": "Chemical analysis / physical properties of the material",
          "properties": "Material properties", "dimensions": "Dimensional inspection (sample of 5 pieces)"}


def generate(record: BatchRecord) -> bytes:
    page = Page()
    y = _header(page, record)
    y = _delivery(page, record, y)
    for group, title in GROUPS.items():
        if record.measurements.get(group):
            y = _table(page, title, record.measurements[group], y)
    _statement(page, record, y)
    company = record.article.company
    return render(page, {"Title": f"Inspection certificate 3.1 {record.certificate}", "Author": company.name,
                         "Subject": f"{record.article.part_id} batch {record.lot}",
                         "CreationDate": "D:" + record.despatched.isoformat().replace("-", "")},
                  producer=f"{company.short_name} supplier portal")


def _header(page: Page, record: BatchRecord) -> float:
    company = record.article.company
    page.rect(0, 0, page.width, 58, BLUE)
    page.text(LEFT, 36, company.name, 17, True, (1, 1, 1))
    page.text(380, 30, "Quality assurance", 9, False, (1, 1, 1))
    page.text(380, 43, f"GLN {company.gln}", 9, False, (1, 1, 1))
    page.text(LEFT, 96, "Inspection certificate 3.1", 20, True)
    page.text(LEFT, 114, "according to EN 10204:2004 (Abnahmeprüfzeugnis 3.1)", 10.5, False, GREY)
    page.text(LEFT, 134, f"Certificate no. {record.certificate}", 10.5, True)
    page.text(330, 134, f"Date of issue {record.despatched}", 10.5, True)
    return 160.0


def _section(page: Page, title: str, y: float) -> float:
    page.text(LEFT, y, title, 11.5, True, BLUE)
    page.line(LEFT, y + 5, page.width - LEFT, y + 5, 0.8, BLUE)
    return y + 20


def _delivery(page: Page, record: BatchRecord, y: float) -> float:
    article = record.article
    y = _section(page, "Delivery", y)
    rows = [("Customer", "VF Pneumatics GmbH, Kaiserslautern"),
            ("Despatch advice", f"{record.despatch_advice} of {record.despatched}"),
            ("Article", f"{article.part_id} - {article.name['en']}"),
            ("Customer part number", article.customer_part_id),
            ("Batch / quantity", f"{record.lot} / {record.quantity} pieces, produced {record.produced}"),
            ("Batch identifier", record.asset_id),
            ("Material", article.profile.get("certificate", {}).get("material", "-"))]
    if record.recycled:
        rows.append(("Recycled content", f"pre-consumer {record.recycled[0]:.0f} %, "
                                         f"post-consumer {record.recycled[1]:.0f} %"))
    for key, value in rows:
        page.text(LEFT, y, key, 9.5, False, GREY)
        page.text(VALUE_X, y, value, 9 if len(value) > 60 else 9.5)
        page.line(LEFT, y + 5, page.width - LEFT, y + 5)
        y += 16
    return y + 12


def _table(page: Page, title: str, rows: tuple[Measurement, ...], y: float) -> float:
    y = _section(page, title, y)
    for x, text in zip(COLUMNS, ("Characteristic", "Unit", "Min", "Max", "Actual")):
        page.text(x, y, text, 8.5, True, GREY)
    y += 14
    for row in rows:
        values = (row.characteristic, row.unit, _num(row.low), _num(row.high), _num(row.actual))
        for x, text in zip(COLUMNS, values):
            page.text(x, y, text, 9)
        page.line(LEFT, y + 4, page.width - LEFT, y + 4)
        y += 14
    return y + 12


def _statement(page: Page, record: BatchRecord, y: float) -> None:
    y = _section(page, "Result", y)
    page.text(LEFT, y, "All characteristics are within the specified limits. Disposition: released.", 10,
              True, GREEN)
    y += 22
    for line in ["We confirm that the products supplied comply with the requirements of the order. The tests",
                 "were carried out on the delivered batch (specific inspection) by the quality assurance",
                 f"department of {record.article.company.name}, independent of manufacturing. The batch",
                 "carbon footprint and material data are published in the batch AAS (supplier environment)."]:
        page.text(LEFT, y, line, 9.5)
        y += 14
    page.line(LEFT, page.height - 52, page.width - LEFT, page.height - 52)
    footer = f"{record.certificate} · page 1/1 · {record.asset_id}"
    page.text(LEFT, page.height - 38, footer, 7.5, False, GREY)


def _num(value: float) -> str:
    return f"{value:.4g}" if abs(value) < 10 else f"{value:.2f}".rstrip("0").rstrip(".")


if __name__ == "__main__":
    from .articles import Catalogue
    from .batches import batch_record

    sample = batch_record(Catalogue().find("DGP_EC32_F"), "DGP-260914-F")
    target = Path(sys.argv[1] if len(sys.argv) > 1 else "aas/files/supplier/MC-DGP-260914-F.pdf")
    target.write_bytes(generate(sample))
