"""Models3D (IDTA Provision of 3D Models) values for the glTF models produced by blender/scripts."""

from __future__ import annotations

from pathlib import PurePosixPath


def models3d_values(spec: dict) -> dict:
    """spec: {file: repo path of the .glb, preview: repo path of a PNG, title, organization, version, date}"""
    org = spec.get("organization", "VF Automation Systems GmbH")
    name = PurePosixPath(spec["file"]).name
    return {"Model3D": [{
        "File": {
            "FileId": [{"FileDomainId": "VirtualFactory", "ValueId": PurePosixPath(spec["file"]).stem,
                        "IsPrimary": [{"value": True}]}],
            "FileVersion": [{
                "Title": {"en": spec.get("title", name)}, "FileName": name,
                "FileVersionId": spec.get("version", "1.0"), "StatusValue": "Released",
                "SetDate": spec.get("date", "2026-10-03"),
                "PreviewFile": f"repo:{spec['preview']}", "DigitalFile": f"repo:{spec['file']}",
                "FileFormat": {"FormatName": "glTF", "FormatVersion": "2.0",
                               "FormatQualifier": "binary (.glb)"},
                "SourceApplication": {"ApplicationName": "Blender", "ApplicationVersion": "5.2",
                                      "ApplicationQualifier": "generated by versioned Python scripts",
                                      "VendorOrganization": {
                                          "OrganizationName": "Blender Foundation",
                                          "OrganizationOfficialName": "Blender Foundation"}},
                "ProvidingOrganization": {"OrganizationName": org.split(" GmbH")[0],
                                          "OrganizationOfficialName": org},
            }],
            "ConsumingApplication": [{"ApplicationName": "Godot Engine", "ApplicationVersion": "4.7",
                                      "ApplicationQualifier": "Virtual Factory runtime "
                                                              "(Compatibility renderer)",
                                      "VendorOrganization": {
                                          "OrganizationName": "Godot Foundation",
                                          "OrganizationOfficialName": "Godot Foundation"}}],
            "FileClassification": [{"ClassId": "3D-VIS", "ClassName": {"en": "3D visualisation model"},
                                    "ClassificationSystem": "VirtualFactory"}],
        },
        "Capability": {"PosModelPurpose": [{"value": p} for p in ("Visualisation", "Virtual commissioning",
                                                                  "Training")],
                       "NegModelPurpose": [{"value": "Manufacturing (not a CAD model)"}],
                       "ObjectType": spec.get("objectType", "Machine"), "Origin": "Designed",
                       "Simplification": {"Description": "Low-poly visual model; parts animated "
                                                         "by the simulation are separate named nodes"}},
        "Geometry": {"Representation": "Mesh", "LengthUnit": "m"},
    }]}
