"""Inspection certificate 3.1 (EN 10204:2004 style) of one produced part: generated by the MES when a good
part is packed, uploaded as File attachment of the workpiece's HandoverDocumentation (item-level passport,
ADR-0021).

Content: product and serial, product id (GS1 Digital Link) and DPP id, production order, dates, the results of
leak test (OP50), function test (OP60) and colour inspection (OP80) against the inspection plan, component
lots, verdict and the issuing quality department. One A4 page, written with the minimal PDF writer (pdf.py).

`uv run python -m mes.certificate [out.pdf]` writes the sample of the blueprint serial PC3280-2026-000123.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

from .lots import COMPONENTS
from vf_common.pdf import Page, render
from .quality import Limits

BLUE, GREY, GREEN, RED = (0.1, 0.27, 0.55), (0.43, 0.45, 0.47), (0.1, 0.5, 0.25), (0.7, 0.12, 0.1)
LEFT, VALUE_X = 50.0, 210.0
COMPONENT_NAMES = {"Barrel": "Barrel", "EndCapFront": "Front end cap", "EndCapRear": "Rear end cap",
                   "PistonRod": "Piston rod", "Piston": "Piston with magnet ring",
                   "SealKit": "Seal kit SK-PC32", "ScrewM5x16": "Socket head cap screws M5x16 (8)",
                   "CushioningScrew": "Cushioning screws (2)", "ProtectiveCap": "Protective cap"}


@dataclass(frozen=True)
class CertificateData:
    serial: str
    issued: str                  # date of issue (packing), ISO date
    manufactured: str            # date of manufacture (release from the cell), ISO date
    order_id: str
    dpp_id: str
    product_id: str
    leak_rate: float
    stroke_time: float
    delta_e: float
    lab_text: str
    limits: Limits = field(default_factory=Limits)
    lots: dict[str, str] = field(default_factory=dict)

    @property
    def number(self) -> str:
        return "IC-" + self.serial

    def results(self) -> list[tuple[str, str, str, bool]]:
        """(characteristic, requirement, measured value, passed) per inspected characteristic."""
        lim = self.limits
        return [
            ("Leak rate at 6 bar, pressure decay (OP50)", f"<= {lim.leak_rate_max:.1f} cm³/min",
             f"{self.leak_rate:.2f} cm³/min", self.leak_rate <= lim.leak_rate_max),
            ("Stroke time at 6 bar, advancing (OP60)",
             f"{lim.stroke_time_min:.2f} – {lim.stroke_time_max:.2f} s", f"{self.stroke_time:.3f} s",
             lim.stroke_time_min <= self.stroke_time <= lim.stroke_time_max),
            ("Colour of protective cap, ΔE*ab CIE76 (OP80)", f"<= {lim.delta_e_max:g}",
             f"{self.delta_e:.1f}", self.delta_e <= lim.delta_e_max)]

    @property
    def passed(self) -> bool:
        return all(r[3] for r in self.results())


def generate(data: CertificateData) -> bytes:
    page = Page()
    y = _header(page, data)
    y = _product(page, data, y)
    y = _results(page, data, y)
    y = _lots(page, data, y)
    _statement(page, data, y)
    return render(page, {"Title": f"Inspection certificate 3.1 {data.number}", "Author": "VF Pneumatics GmbH",
                         "Subject": f"PC-32-80-DA-M serial {data.serial}",
                         "CreationDate": "D:" + data.issued.replace("-", "")})


def _header(page: Page, data: CertificateData) -> float:
    page.rect(0, 0, page.width, 58, BLUE)
    page.text(LEFT, 36, "VF Pneumatics GmbH", 17, True, (1, 1, 1))
    page.text(370, 30, "Quality department", 9, False, (1, 1, 1))
    page.text(370, 43, "Fabrikstraße 1, 67655 Kaiserslautern, DE", 9, False, (1, 1, 1))
    page.text(LEFT, 96, "Inspection certificate 3.1", 20, True)
    page.text(LEFT, 114, "according to EN 10204:2004 (Abnahmeprüfzeugnis 3.1)", 10.5, False, GREY)
    page.text(LEFT, 134, f"Certificate no. {data.number}", 10.5, True)
    page.text(330, 134, f"Date of issue {data.issued}", 10.5, True)
    return 160.0


def _section(page: Page, title: str, y: float) -> float:
    page.text(LEFT, y, title, 12, True, BLUE)
    page.line(LEFT, y + 5, page.width - LEFT, y + 5, 0.8, BLUE)
    return y + 22


def _row(page: Page, key: str, value: str, y: float) -> float:
    page.text(LEFT, y, key, 9.5, False, GREY)
    page.text(VALUE_X, y, value, 9.5)
    page.line(LEFT, y + 5, page.width - LEFT, y + 5)
    return y + 17


def _product(page: Page, data: CertificateData, y: float) -> float:
    y = _section(page, "Product", y)
    rows = [("Product", "Profile cylinder ISO 15552 PC-32-80-DA-M, article 5032-0080"),
            ("Serial number", data.serial), ("Product identifier", data.product_id),
            ("Digital product passport", data.dpp_id),
            ("Production order", data.order_id or "none (line operated without production order)"),
            ("Date of manufacture", f"{data.manufactured}, LINE01 (assembly and test cell AC01, QS01)")]
    for key, value in rows:
        y = _row(page, key, value, y)
    return y + 14


def _results(page: Page, data: CertificateData, y: float) -> float:
    y = _section(page, "Test results (inspection plan IP-PC3280 1.0, data sheet DS-PC3280)", y)
    columns = (LEFT, 275.0, 385.0, 480.0)
    for x, title in zip(columns, ("Characteristic", "Requirement", "Measured", "Result")):
        page.text(x, y, title, 9, True, GREY)
    y += 16
    for characteristic, requirement, measured, ok in data.results():
        for x, text in zip(columns, (characteristic, requirement, measured)):
            page.text(x, y, text, 9.5)
        page.text(columns[3], y, "passed" if ok else "failed", 9.5, True, GREEN if ok else RED)
        page.line(LEFT, y + 5, page.width - LEFT, y + 5)
        y += 17
    page.text(LEFT, y, f"Measured cap colour {data.lab_text} (reference L* 42.3, a* 64.4, b* 46.6, D65/2°).",
              8.5, False, GREY)
    return y + 26


def _lots(page: Page, data: CertificateData, y: float) -> float:
    y = _section(page, "Traceability: component lots", y)
    for node, article in COMPONENTS.items():
        page.text(LEFT, y, f"{COMPONENT_NAMES[node]} ({article})", 9.5, False, GREY)
        page.text(VALUE_X + 60, y, data.lots.get(node, "-"), 9.5)
        y += 14
    return y + 14


def _statement(page: Page, data: CertificateData, y: float) -> None:
    y = _section(page, "Result", y)
    verdict = "meets" if data.passed else "does NOT meet"
    lines = [f"We confirm that the product {verdict} the requirements of the order and of the specification",
             "stated above. The tests were carried out on the delivered unit (specific inspection).",
             f"Disposition: {'accepted' if data.passed else 'rejected'}."]
    for line in lines:
        page.text(LEFT, y, line, 10, line.startswith("Disposition"), GREEN if data.passed else RED)
        y += 15
    y += 14
    for line in ["Issued by the quality department of VF Pneumatics GmbH (independent of production),",
                 "authorised inspection representative: Quality Management. This certificate was generated",
                 "electronically by the MES and is valid without signature."]:
        page.text(LEFT, y, line, 9.5)
        y += 14
    page.line(LEFT, page.height - 52, page.width - LEFT, page.height - 52)
    page.text(LEFT, page.height - 38, f"{data.number} · page 1/1 · part of the digital product passport "
              f"{data.dpp_id}", 7.5, False, GREY)


def sample() -> CertificateData:
    """Certificate of the blueprint part PC3280-2026-000123 (aas/data/blueprints/workpiece_instance.yaml)."""
    lots = {"Barrel": "L2609-0419", "EndCapFront": "DGP-260914-F", "EndCapRear": "DGP-260915-R",
            "PistonRod": "L2609-2411", "Piston": "L2609-3387", "SealKit": "DTS-2608-1173",
            "ScrewM5x16": "NRN-26-33871", "CushioningScrew": "L2609-5370", "ProtectiveCap": "KTW-26-0911"}
    return CertificateData(
        serial="PC3280-2026-000123", issued="2026-10-01", manufactured="2026-10-01", order_id="PO-0001",
        dpp_id="https://virtual-factory.example/ids/aas/WP_PC3280_2026_000123",
        product_id="https://virtual-factory.example/01/04099999032808/21/PC3280-2026-000123",
        leak_rate=0.38, stroke_time=0.321, delta_e=3.1, lab_text="L* 43.9, a* 62.1, b* 45.2", lots=lots)


if __name__ == "__main__":
    target = Path(sys.argv[1] if len(sys.argv) > 1 else "aas/files/docs/IC-PC3280-2026-000123.pdf")
    target.write_bytes(generate(sample()))
    print(f"wrote {target} ({target.stat().st_size} bytes)")
