#!/usr/bin/env python3
"""Generates docs/interfaces/device-catalog.md from all FMI modelDescription.xml files and the line layout.

Usage: uv run tools/gen_interface_docs.py [--check]   (--check: fail if the file is out of date)
"""

from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GODOT = ROOT / "godot"
OUT = ROOT / "docs" / "interfaces" / "device-catalog.md"
LAYOUT = GODOT / "config" / "layouts" / "line1.layout.json"
VAR_TAGS = ("Float64", "Int32", "UInt64", "Boolean", "String")
CAUSALITY_ORDER = {"input": 0, "parameter": 1, "output": 2, "local": 3, "independent": 4}


def model_files() -> list[Path]:
    return sorted(p for p in GODOT.rglob("modelDescription.xml")
                  if ".godot" not in p.parts and "tests" not in p.parts)


def start_value(var: ET.Element) -> str:
    if var.tag == "String":
        start = var.find("Start")
        return f'"{start.get("value", "")}"' if start is not None else ""
    return var.get("start", "")


def model_section(path: Path) -> list[str]:
    root = ET.parse(path).getroot()
    rel = path.relative_to(GODOT).as_posix()
    lines = [f"## {root.get('modelName')}", "",
             f"{root.get('description', '')}", "",
             f"- Model description: `godot/{rel}`",
             f"- modelIdentifier: `{root.find('CoSimulation').get('modelIdentifier')}` · "
             f"instantiationToken: `{root.get('instantiationToken')}`", "",
             "| VR | Name | Causality | Variability | Type | Unit | Start | Description |",
             "|---:|---|---|---|---|---|---|---|"]
    variables = [v for v in root.find("ModelVariables") if v.tag in VAR_TAGS]
    variables.sort(key=lambda v: (CAUSALITY_ORDER.get(v.get("causality"), 9), int(v.get("valueReference"))))
    for v in variables:
        if v.get("causality") == "independent":
            continue
        desc = (v.get("description") or "").replace("|", "\\|")
        lines.append(f"| {v.get('valueReference')} | `{v.get('name')}` | {v.get('causality')} | "
                     f"{v.get('variability')} | {v.tag} | {v.get('unit', '')} | {start_value(v)} | {desc} |")
    return lines + [""]


def layout_section() -> list[str]:
    layout = json.loads(LAYOUT.read_text())
    lines = [f"## Line layout `{layout['line']}`", "", layout.get("description", ""), "",
             "| Device | Type | Position (m) |", "|---|---|---|"]
    for d in layout["devices"]:
        lines.append(f"| {d['id']} | `{d['type']}` | {tuple(d.get('position', [0, 0, 0]))} |")
    lines += ["", "### Signal connections (FMI variable wiring, Gauss-Seidel order = device order, PLC last)", "",
              "| From (output) | To (input) |", "|---|---|"]
    lines += [f"| `{a}` | `{b}` |" for a, b in layout["connections"]]
    lines += ["", "### Teach points (commissioning)", "", "| Device parameter | Marker |", "|---|---|"]
    lines += [f"| `{t['device']}.{t['parameter']}_x/y/z` | `{t['marker']}` |" for t in layout.get("teach", [])]
    return lines + [""]


def render() -> str:
    lines = ["# Device interface catalogue", "",
             "> Generated by `tools/gen_interface_docs.py` from the FMI 3.0 model descriptions and the layout. "
             "Do not edit by hand.", ""]
    for path in model_files():
        lines += model_section(path)
    lines += layout_section()
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != content:
            print(f"{OUT.relative_to(ROOT)} is out of date; run tools/gen_interface_docs.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
