"""Mosquitto accounts of the secure profile: ACL file (per user: deny, then read/write patterns) and the plain
password list that the broker container hashes at start (`mosquitto_passwd -U`), ADR-0027.
Topic templates: {root} = topic_root of godot/config/uns.json, {opcua_device} = each controller on the OPC UA
path (opcua.servers, lower case)."""

from __future__ import annotations


def mqtt_password(user: str) -> str:
    return f"{user}-local-secret"


def _expand(pattern: str, uns: dict) -> list[str]:
    root = uns["topic_root"]
    devices = [d.lower() for d in (uns.get("opcua", {}).get("servers") or {})]
    expanded = pattern.replace("{root}", root)
    if "{opcua_device}" in expanded:
        return [expanded.replace("{opcua_device}", d) for d in devices]
    return [expanded]


def acl(model: dict, uns: dict) -> str:
    lines = ["# Generated by tools/gen_security_config.py from infra/security.yaml - do not edit.",
             "# Mosquitto ACL of the secure profile (ADR-0027). No anonymous access (mosquitto.conf).", ""]
    for user, spec in model["mqtt"].items():
        lines.append(f"user {user}")
        for kind in ("deny", "write", "read"):
            for pattern in spec.get(kind, []):
                lines += [f"topic {kind} {topic}" for topic in _expand(pattern, uns)]
        lines.append("")
    return "\n".join(lines)


def passwords(model: dict) -> str:
    """user:password lines (local defaults, O34); hashed in the container before mosquitto starts."""
    return "".join(f"{user}:{mqtt_password(user)}\n" for user in model["mqtt"])
